apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: cardconfirmedsubscription
spec:
  topic: orchestratortopic
  route: /Orchestrator/cardconfirmed
  pubsubname: pubsub
scopes:
- orchestrator

---

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: newcardsubscription
spec:
  topic: cardtopic
  route: /Card
  pubsubname: pubsub
scopes:
- card
